name: evon_calories_tracker
description: Evon Calories Tracker

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  #  sdk: ">=3.0.0 <3.5.0"
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  animated_login: ^1.5.5
  http: ^0.13.5
  flutter_easyloading: ^3.0.5
  flutter_sms: ^2.3.3
  flutter_super_state: ^0.2.0
  sqflite: ^2.2.0+3
  font_awesome_flutter: ^10.2.1
  flutter_login: ^4.1.0
  intl: ^0.17.0
  rflutter_alert: ^2.0.4
  fluttericon: ^2.0.0
  equatable: ^2.0.5
  select_form_field: ^2.2.0
  flutter_spinkit: ^5.1.0
  wc_form_validators: ^1.0.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.2
  flutter_secure_storage: ^6.1.0
  image_picker: ^0.8.6
  flutter_sticky_header: ^0.6.4
  datetime_picker_formfield: ^2.0.1
  avatar_view: ^1.0.1
  flutter_inappwebview: ^5.7.2+2

  json_annotation: ^4.4.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  charts_common: ^0.12.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.50.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/shapes/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
